# Generated by Django 4.0.6 on 2022-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=20)),
                ('phone_number', models.IntegerField()),
                ('driver_image', models.ImageField(upload_to='driver/images')),
                ('vehicle_no', models.CharField(max_length=10)),
                ('license_no', models.CharField(max_length=10)),
                ('insurance_no', models.CharField(max_length=10)),
                ('earnings', models.IntegerField()),
                ('all_rides', models.CharField(max_length=1000)),
                ('last_location_lat', models.IntegerField()),
                ('last_location_long', models.IntegerField()),
                ('current_location_lat', models.IntegerField()),
                ('current_location_long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=20)),
                ('phone_number', models.IntegerField()),
                ('user_image', models.ImageField(upload_to='user/images')),
                ('home_address', models.CharField(max_length=400)),
                ('work_address', models.CharField(max_length=400)),
                ('all_rides', models.CharField(max_length=1000)),
            ],
        ),
    ]
