# Generated by Django 4.0.6 on 2022-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location_lat', models.IntegerField()),
                ('pickup_location_long', models.IntegerField()),
                ('drop_location_lat', models.IntegerField()),
                ('drop_location_long', models.IntegerField()),
                ('duration', models.DurationField()),
                ('distance_in_km', models.IntegerField()),
                ('price', models.IntegerField()),
                ('user_id', models.CharField(max_length=10)),
                ('driver_id', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ARRIVED', 'ARRIVED'), ('ARRIVING', 'ARRIVING'), ('CANCELLED', 'CANCELLED')], default='ARRIVED', max_length=20)),
            ],
        ),
    ]
