# Generated by Django 4.0.6 on 2022-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_driver_last_location_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='current_location_lat',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_location_long',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_location_lat',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_location_long',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='ride_details',
            name='drop_location_lat',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='ride_details',
            name='drop_location_long',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='ride_details',
            name='pickup_location_lat',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='ride_details',
            name='pickup_location_long',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
    ]
