# Generated by Django 4.0.6 on 2022-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_driver_current_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
