# Generated by Django 4.0.6 on 2022-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_driver_driver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_image',
            field=models.ImageField(blank=True, default='def_img.png', null=True, upload_to='driver/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='driver/images/def_img.png', null=True, upload_to='driver/images'),
        ),
    ]
