# Generated by Django 4.0.6 on 2022-10-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_driver_driver_image_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='User_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='def_img.png', null=True, upload_to='driver/images'),
        ),
    ]
