# Generated by Django 4.0.6 on 2022-10-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_driver_user_id_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
