# Generated by Django 4.1.2 on 2022-11-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_promo_code_all_ride_historie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ride_historie',
            name='Cancel_Ride',
            field=models.CharField(choices=[('DRIVER DENIED TO COME', 'DRIVER DENIED TO COME'), ('ASKING FOR EXTRA MONEY', 'ASKING FOR EXTRA MONEY'), ('BOOKED FROM SOMEWHERE ELSE', 'BOOKED FROM SOMEWHERE ELSE'), ('CHANGE OF PLAN', 'CHANGE OF PLAN'), ('OTHER', 'OTHER')], default='NONE', max_length=50),
        ),
    ]
