# Generated by Django 4.1.2 on 2022-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_all_ride_historie_cancel_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ride_historie',
            name='status',
            field=models.CharField(choices=[('ARRIVED', 'ARRIVED'), ('ARRIVING', 'ARRIVING'), ('CANCELLED', 'CANCELLED'), ('ENDED', 'ENDED'), ('ADVANCE BOOKING', 'ADVANCE BOOKING')], default='ARRIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride_details',
            name='status',
            field=models.CharField(choices=[('ARRIVED', 'ARRIVED'), ('ARRIVING', 'ARRIVING'), ('CANCELLED', 'CANCELLED'), ('ENDED', 'ENDED'), ('ADVANCE BOOKING', 'ADVANCE BOOKING')], default='ARRIVED', max_length=20),
        ),
    ]
