# Generated by Django 4.1.2 on 2022-11-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_delete_ride_details_remove_driver_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_ride_historie',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='total_rides',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_rides',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_address',
        ),
        migrations.AddField(
            model_name='all_ride_historie',
            name='Driver_Uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='all_ride_historie',
            name='Ride',
            field=models.CharField(blank=True, choices=[('Luxury', 'Luxury'), ('Ride Mini', 'Ride Mini'), ('Ride AC', 'Ride AC'), ('Bike', 'Bike')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='all_ride_historie',
            name='User_Uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='UId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='UId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
