# Generated by Django 4.1.2 on 2022-11-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_all_ride_historie_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ride_historie',
            name='Ride_Time',
            field=models.TimeField(null=True),
        ),
    ]
