# Generated by Django 4.1.2 on 2022-11-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_all_ride_historie_ride_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ride_historie',
            name='Carpooling',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
