# Generated by Django 4.1.2 on 2022-11-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_all_ride_historie_carpooling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_ride_historie',
            name='Carpooling',
        ),
        migrations.AddField(
            model_name='all_ride_historie',
            name='Carpooling_User_1_Uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='all_ride_historie',
            name='Carpooling_User_2_Uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='all_ride_historie',
            name='Carpooling_User_3_Uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
