# Generated by Django 4.1.2 on 2022-11-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_ride_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_offer',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ride_offer',
            name='Ride_Time',
            field=models.TimeField(null=True),
        ),
    ]
