# Generated by Django 4.1.2 on 2022-11-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_ride_offer_date_ride_offer_ride_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_offer',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride_offer',
            name='Ride_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Driver_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('driver_image', models.ImageField(blank=True, default='def_img.png', null=True, upload_to='driver/images')),
                ('vehicle_no', models.CharField(max_length=10)),
                ('vehicle_name', models.CharField(default='', max_length=50)),
                ('license_no', models.CharField(max_length=10)),
                ('insurance_no', models.CharField(max_length=10)),
                ('Driver_offer', models.IntegerField()),
                ('Ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.all_ride_historie')),
            ],
        ),
    ]
