# Generated by Django 3.2.9 on 2022-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_ride_offer_date_alter_ride_offer_ride_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='total_rides',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
