# Generated by Django 3.2.9 on 2022-11-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20221129_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ride_historie',
            name='Driver_Detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.driver'),
        ),
    ]
