# Generated by Django 3.2.9 on 2022-12-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_all_ride_historie_driver_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ride_historie',
            name='Fragile',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_ride_historie',
            name='Ride_Type',
            field=models.CharField(blank=True, choices=[('RIDE', 'RIDE'), ('DELIVERY', 'DELIVERY')], max_length=20, null=True),
        ),
    ]
