# Generated by Django 3.2.9 on 2022-12-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20221206_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ride_historie',
            name='Ride_Type',
            field=models.CharField(choices=[('RIDE', 'RIDE'), ('DELIVERY', 'DELIVERY')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
