# Generated by Django 4.1.4 on 2022-12-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_driver_message_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='looking_rides',
            field=models.BooleanField(default=False),
        ),
    ]
