# Generated by Django 4.1.4 on 2022-12-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_all_ride_historie_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ride_historie',
            name='Drop_Address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
