# Generated by Django 4.1.4 on 2022-12-24 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_all_ride_historie_drop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ratings',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
