# Generated by Django 4.1.4 on 2022-12-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_driver_offer_address_driver_offer_drop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_offer',
            name='Address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_offer',
            name='Drop_Address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
