# Generated by Django 4.1.4 on 2022-12-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_ride_offer_address_ride_offer_drop_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=40)),
                ('long', models.DecimalField(decimal_places=8, max_digits=40)),
                ('address', models.CharField(max_length=400)),
            ],
        ),
    ]
